apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: prisma
spec:
  type: ClusterIP
  selector:
    component: "db"
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP