apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prisma
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard