apiVersion: v1
kind: Service
metadata:
  namespace: prisma
  name: prisma
spec:
  type: ClusterIP
  selector:
    component: prisma
  ports:
  - name: prisma-port
    port: 4466
    targetPort: 4466
    protocol: TCP